config/routes.rb
Rails.application.routes.draw do
  get 'questions/confirmation'
  get 'questions/instructions'
  get 'questions/survey'
  get 'users/login'
  root 'users#login'
  resources :optionals
  resources :feedbacks
  resources :questions
  resources :responses
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    validates :to_ask, :option_1, :option_2, :option_3, presence: true
    validates :question_id, numericality: { greater_than: -1 }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Calculations
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:survey, :instructions, :confirmation]
  before_action :credentials?, only: [:survey, :instructions, :confirmation]
  before_action :admin?, except: [:create, :survey, :instructions, :confirmation]
  before_action :set_multiplier, only: [:survey, :confirmation]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order(sort_column(Question) + ' ' + sort_direction)
    @question = Question.new
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create

    # if admin is creating a new question
    if params[:new].to_i == 1
        q = Question.new(question_id: params[:question][:question_id], to_ask: params[:question][:to_ask], 
                        option_1: params[:question][:option_1], option_2: params[:question][:option_2], 
                        option_3: params[:question][:option_3])

        respond_to do |format|

            # pass through validation
            if q.save
                format.html { redirect_to index, notice: 'Question was successfully updated.' }
                format.js
            else
                format.html { redirect_to index }
                format.json { render json: @q.errors, status: :unprocessable_entity }

            end
        end
    else

        # find the question the user is currently reading
        question = Question.find_by(question_id: cookies.signed[@current_user.user_id])

        # record the user's response and save it to the database
        response = Response.new(question_id: question.question_id, user_id: @current_user.user_id, 
                    is_gamified: @current_user.is_gamified, selection: params[:selection], 
                    response_text: params[:response_text])

        # check if the user has selected an option
        if response.save

            # set the user's flag for the specific question as complete
            @current_user.update(completed: @current_user.completed | (1 << question.question_id))

            # delete the question id from cookie sorage
            cookies.delete(@current_user.user_id)

            # find another question for the user
            redirect_to '/questions/survey' and return

        # otherwise do not continue or mark question as completed
        else
            flash.now[:danger] = 'Please select an option'
        end

    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /questions/confirmation
  def confirmation

    # calculate corresponding point totals
    @user_point_total = (calculate_user(@current_user) * @multiplier).floor
    @em_point_total = (calculate_all("Emergency Medicine") * 2.4).floor
    @fm_point_total = (calculate_all("Family Medicine") * 1.7).floor
    @gim_point_total = calculate_all("General Internal Medicine")
    @pcc_point_total = (calculate_all("Pulmonary Critical Care") * 6.0).floor
    @team_point_total = case @current_user.department
        when "Emergency Medicine"
            @em_point_total
        when "Family Medicine"
            @fm_point_total
        when "General Internal Medicine"
            @gim_point_total
        when "Pulmonary Critical Care"
            @pcc_point_total
    end

    # variables for displaying patient state
    @question_total = Question.all.count.to_f
    @patient_state = calculate_user_q(@current_user) / @question_total
  end

  # GET /questions/instructions
  def instructions
  end

  # GET /questions/survey
  def survey

    # check if the user already has a cookie for their last saved question
    next_question = cookies.signed[@current_user.user_id] ? cookies.signed[@current_user.user_id] : random(@current_user)

    # calculate point totals for the user
    @user_point_total = (calculate_user(@current_user) * @multiplier).floor

    # calculate point totals for each team
    @em_point_total = (calculate_all("Emergency Medicine") * 2.4).floor
    @fm_point_total = (calculate_all("Family Medicine") * 1.7).floor
    @gim_point_total = calculate_all("General Internal Medicine")
    @pcc_point_total = (calculate_all("Pulmonary Critical Care") * 6.0).floor

    # set the question for the user
    @question = Question.find_by(question_id: next_question)

    # variables for displaying patient state
    @question_total = Question.all.count.to_f
    @patient_state = calculate_user_q(@current_user) / @question_total

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:is_gamified, :question_id, :to_ask)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.number_field :question_id %>
  </div>

  <div class="field">
    <%= form.label :to_ask %>
    <%= form.text_area :to_ask %>
  </div>

  <div class="field">
    <%= form.label :option_1 %>
    <%= form.text_area :option_1 %>
  </div>

  <div class="field">
    <%= form.label :option_2 %>
    <%= form.text_area :option_2 %>
  </div>

  <div class="field">
    <%= form.label :option_3 %>
    <%= form.text_area :option_3 %>
  </div>

  <%= hidden_field_tag 'new', 1 %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/confirmation.html.erb
<h3 class="text-center">Are you sure you want to exit?</h3>

<div class="text-center">
   <p><%= link_to 'Return', '/questions/survey' %> &nbsp <%= link_to 'Exit', :new_feedback %></p>
</div>

<% if @current_user.is_gamified %>
    <div class="row">
        <div class="column side">
            <div class="flex-container">
                <div class="confirmation">
                    <h2>Your points:</h2>
                    <h1><%= @user_point_total %></h1>
                </div>
            </div>
        </div>
        <div class="column middle">
            <div class="flex-container">
                <div class="confirmation">
                    <h2>Your department's points:</h2>
                    <h1><%= @team_point_total %></h1>
                </div>
            </div>
            <%= pie_chart [["Emergency Medicine", @em_point_total], ["Family Medicine", @fm_point_total],
                            ["General Internal Medicine", @gim_point_total], ["Pulmonary Critical Care", @pcc_point_total]], 
                colors: ["blue", "green", "yellow", "red"], 
                library: {pieSliceText: "value-and-percentage"} %>
        </div>
        <div class="column-side">            
            <div class="flex-container">
                <div class="confirmation">
                    <h2>Patient State:</h2>
                    <% if @patient_state >= 0 and @patient_state < 0.2 %>
                        <%= image_tag "Patient_1.png", :size => "300" %>
                    <% elsif @patient_state >= 0.2 and @patient_state < 0.4 %>
                        <%= image_tag "Patient_2.png", :size => "300" %>
                    <% elsif @patient_state >= 0.4 and @patient_state < 0.6 %>
                        <%= image_tag "Patient_3.png", :size => "300" %>
                    <% elsif @patient_state >= 0.6 and @patient_state < 0.8 %>
                        <%= image_tag "Patient_4.png", :size => "300" %>
                    <% elsif @patient_state >= 0.8 and @patient_state <= 1 %>
                        <%= image_tag "Patient_5.png", :size => "300" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= sortable "question_id", Question %></th>
      <th><%= sortable "to_ask", Question %></th>
      <th><%= sortable "option_1", Question %></th>
      <th><%= sortable "option_2", Question %></th>
      <th><%= sortable "option_3", Question %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question_id %></td>
        <td><%= question.to_ask %></td>
        <td><%= question.option_1 %></td>
        <td><%= question.option_2 %></td>
        <td><%= question.option_3 %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="flex-container">
    <div class="text-center">
        <%= form_with(model: @question, local: true) do |form| %>
    
        <% if @question.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

                <ul>
                <% @question.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
                </ul>
            </div>
        <% end %>

        <h5>Please make sure questions are numbered consecutively from 0 to n</h5>

        <div class="field">
            <%= form.label :question_id, "Question ID" %><br>
            <%= form.number_field :question_id %>
        </div>

        <div class="field">
            <%= form.label :to_ask, "Question" %><br>
            <%= form.text_area :to_ask %>
        </div>

        <div class="field">
            <%= form.label :option_1 %><br>
            <%= form.text_area :option_1 %>
        </div>

        <div class="field">
            <%= form.label :option_2 %><br>
            <%= form.text_area :option_2 %>
        </div>

        <div class="field">
            <%= form.label :option_3 %><br>
            <%= form.text_area :option_3 %>
        </div>

        <%= hidden_field_tag 'new', 1 %>

        <br>
        <div class="actions">
            <%= form.submit %>
        </div>
        <% end %>
    </div>
</div>
<br>
<%= link_to 'Back', :responses %>

app/views/questions/instructions.html.erb
<div class="row">
    <div class="column side">
        <% if @current_user.is_gamified %>
            <div class="flex-container">
                <% if @current_user.department.eql?("Emergency Medicine") %>
                    <div class="margin-lg">
                        8 current points
                    </div>
                    <%= image_tag "ER_Avatar.png", :size => "60x100" %> 
                    <p>14 department points</p>
                <% elsif @current_user.department.eql?("Family Medicine") %>
                    <div class="margin-lg">
                        8 current points
                    </div>
                    <%= image_tag "Family_Doctor_Avatar.png", :size => "60x100" %> 
                    <p>17 department points</p>
                <% elsif @current_user.department.eql?("General Internal Medicine") %>
                    <div class="margin-lg">
                        8 current points
                    </div>
                    <%= image_tag "General_Doctor_Avatar.png", :size => "60x100" %> 
                    <p>12 department points</p>
                <% else %>
                    <div class="margin-lg">
                        8 current points
                    </div>
                    <%= image_tag "Critical_Care_Avatar.png", :size => "60x100" %> 
                    <p>24 department points</p>
                <% end %>
            </div>
            <br>
            <div class="question">
                <p class="text-center">This section shows your current score as well as your department's score.</p>
            </div>
        <% end %>

        <div class="text-left">
            <%= link_to "Continue", '/questions/survey' %>
        </div>
    </div>

    <div class="column middle">
        <h3>
            <center>
                <b>Instructions</b>
            </center>
        </h3>
        <% if @current_user.is_gamified %>
            <div class="container">
                <div class="question">
                    Thank you for participating in this survey. This survey includes a cooperative competition between 
                    your department and 3 other departments. The goal of the competition is to be the department with 
                    the greatest number of points. 
                    <br>
                    <br>
                    This survey consists of 5 clinical vignettes. Each vignette is a patient in the Emergency Room 
                    needing to be triaged. Each vignette will have 3 multiple choice options for where the patient 
                    should be transferred to. These options will be the same for all vignettes. Each vignette you 
                    answer will award you and your department a set number of points. Additionally, you may add an 
                    optional short answer response (500-character limit) to provide more detail to your response. If 
                    you do add a short answer of at least 40 characters, the points you and your department receive 
                    will be doubled for that response. Every question you respond to will be recorded.
                    <br>
                    <br>
                    All images on this page are example images to explain what you will see. On the top left side of 
                    the page you will see from left to right: Your point total, your department avatar, your 
                    department point total. On the right side of the page you will see from top to bottom: The health 
                    state of your patient (which improves for each question you answer), and the graph showing the 
                    point total of all departments. All of this is updated everytime you open a vignette.
                    <br>
                    <br>
                    On each survey question, you may click “View Instructions” to come back to this page, “Continue” 
                    to move onto the next question, or “Save and Exit” to quit the survey. When you quit the survey, 
                    you will be asked some brief questions about your experience. You will be brought back to the last 
                    question you were on if you decide to log-in again.
                    <br>
                    <br>
                    The winning department of this competition will be announced to participants of this survey through 
                    an email after the survey period has closed. Any unfair methods of gaining points will not count 
                    towards the post survey point totals.
                    <br>
                    <br>
                    Once you click “Continue” on the bottom left, you will be taken to the survey questions. Once you 
                    complete the survey, you will not be able to access this page again.
                </div>
            </div>
        <% else %>
            <div class="container">
                <div class="question">
                    Thank you for participating in this survey. This survey consists of 5 clinical vignettes. Each
                    vignette is a patient in the Emergency Room needing to be triaged. Each vignette will have 3
                    multiple choice options for where the patient should be transferred to. These options will be the
                    same for all vignettes. Additionally, you may add an optional short answer response (500-
                    character limit) to provide more detail to your response. Every question you respond to will be
                    recorded.
                    <br>
                    <br>
                    On each survey question, you may click “View Instructions” to come back to this page,
                    “Continue” to move onto the next question, or “Save and Exit” to quit the survey. When you quit
                    the survey, you will be asked some brief questions about your experience. You will be brought
                    back to the last question you were on if you decide to log-in again.
                    <br>
                    <br>
                    Once you click “Continue” on the bottom left, you will be taken to the survey questions. Once
                    you complete the survey, you will not be able to access this page again.
                </div>
            </div>
        <% end %>
    </div>

    <div class="column side">
        <% if @current_user.is_gamified %>
            <div class="flex-container">
                <%= image_tag "Patient_4.png", :size => "190" %>
            </div>
            <div class="flex-container">
                <div class="avatar-margin">
                    <%= image_tag "ER_Avatar.png", :size => "45x75" %>
                </div>
                <div class="avatar-margin">
                    <%= image_tag "Family_Doctor_Avatar.png", :size => "45x75" %>
                </div>
                <div class="avatar-margin">
                    <%= image_tag "General_Doctor_Avatar.png", :size => "45x75" %>
                </div>
                <div class="avatar-margin">
                    <%= image_tag "Critical_Care_Avatar.png", :size => "45x75" %>
                </div>
            </div>
            <div class="flex-container">
                <script type="text/javascript">
                google.charts.load("current", {packages:['corechart']});
                google.charts.setOnLoadCallback(drawChart);
                    function drawChart() {
                        var data = google.visualization.arrayToDataTable([
                            ["Department", "Points", { role: "style" } ],
                            ["Emergency Medicine", 14, "blue"],
                            ["Family Medicine", 17, "green"],
                            ["General Internal Medicine", 12, "yellow"],
                            ["Pulmonary Critical Care", 24, "red"]
                        ]);
                        
                        var view = new google.visualization.DataView(data);
                        view.setColumns([0, 1,
                            {
                                calc: "stringify",
                                sourceColumn: 1,
                                type: "string",
                                role: "annotation"
                            },
                        2]);
                        
                        var options = {
                            bar: {groupWidth: "95%"},
                            legend: { position: "none" },
                        };
                        var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
                        chart.draw(view, options);
                }
                </script>
                <div id="columnchart_values"></div>
            </div>
            <br>
            <div class="question">
                <p class="text-center">This section displays the patient's current state as well as both departments' scores.</p>
            </div>
        <% end %>
    </div>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', :responses %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<form action="/questions#create", method="POST">

    <p><%= @question.question %></p>
    <p>
        <input type="radio" name="response" value="1">
        <%= @question.option_1 %>
    </p>
    <p>
        <input type="radio" name="response" value="2">
        <%= @question.option_2 %>
    </p>
    <p>
        <input type="radio" name="response" value="3">
        <%= @question.option_3 %>
    </p>
    <p><textarea name="response_text" maxlength="255" rows="5"></textarea></p>
    <p><input type="submit" value="Submit"></p>

</form>

app/views/questions/survey.html.erb
<div class="row">
<div class="column side">
    <div class="flex-container">
        <% if @current_user.is_gamified %>
            <div class="margin-lg">
                <%= @user_point_total %> current points
            </div>
            <% if @current_user.department.eql?("Emergency Medicine") %>
                <%= image_tag "ER_Avatar.png", :size => "60x100" %> 
                <%= @em_point_total %>
            <% elsif @current_user.department.eql?("Family Medicine") %>
                <%= image_tag "Family_Doctor_Avatar.png", :size => "60x100" %> 
                <%= @fm_point_total %>
            <% elsif @current_user.department.eql?("General Internal Medicine") %>
                <%= image_tag "General_Doctor_Avatar.png", :size => "60x100" %> 
                <%= @gim_point_total %>
            <% else %>
                <%= image_tag "Critical_Care_Avatar.png", :size => "60x100" %> 
                <%= @pcc_point_total %>
            <% end %>
            department points
        <% else %>
            &nbsp
        <% end %>
    </div>

    <div class="text-left">
        <%= link_to 'View Instructions', '/questions/instructions' %>
    </div>
</div>

<div class="column middle">
    <form action="/questions#create", method="POST">
    <div class="response">
        <div class="row">
            <div class="container">
                <div class="container-border">
                    <div class="container-size-lg">
                        <div class="question">
                            <p><%= @question.to_ask %></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <div class="container-border">
                    <div class="container-size-sm">
                        <ol>
                            <li><input type="radio" name="selection" value="1">
                            <%= @question.option_1 %></li>
                            <li><input type="radio" name="selection" value="2">
                            <%= @question.option_2 %></li>
                            <li><input type="radio" name="selection" value="3">
                            <%= @question.option_3 %></li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="container-border">
                    <div class="container-size-sm">
                        <textarea name="response_text" maxlength="500" placeholder="Optional Comments (Character limit 500)"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="flex-container">
            <p><input type="submit" value="Continue"></p>
        </div>
    </div>
</form>
</div>

<div class="column side">
    <% if @current_user.is_gamified %>
        <div class="flex-container">
            <% if @patient_state >= 0 and @patient_state < 0.2 %>
                <%= image_tag "Patient_1.png", :size => "190"%>
            <% elsif @patient_state >= 0.2 and @patient_state < 0.4 %>
                <%= image_tag "Patient_2.png", :size => "190"%>
            <% elsif @patient_state >= 0.4 and @patient_state < 0.6 %>
                <%= image_tag "Patient_3.png", :size => "190"%>
            <% elsif @patient_state >= 0.6 and @patient_state < 0.8 %>
                <%= image_tag "Patient_4.png", :size => "190"%>
            <% elsif @patient_state >= 0.8 and @patient_state <= 1 %>
                <%= image_tag "Patient_5.png", :size => "190"%>
            <% end %>
        </div>
        <div class="minor-container">
        <div class="flex-margin">
                <%= image_tag "ER_Avatar.png", :size => "45x75" %>
                <%= image_tag "Family_Doctor_Avatar.png", :size => "45x75" %>
                <%= image_tag "General_Doctor_Avatar.png", :size => "45x75" %>
                <%= image_tag "Critical_Care_Avatar.png", :size => "45x75" %>
        </div>
        </div>
        <div class="flex-container">
             <script type="text/javascript">
                var chart;
                var view;
                var options;
                google.charts.load("current", {packages:['corechart']});
                google.charts.setOnLoadCallback(drawChart);
                function drawChart() {
                    var data = google.visualization.arrayToDataTable([
                        ["Department", "Points", { role: "style" } ],
                        ["Emergency Medicine", <%= @em_point_total %>, "blue"],
                        ["Family Medicine", <%= @fm_point_total %>, "green"],
                        ["General Internal Medicine", <%= @gim_point_total %>, "yellow"],
                        ["Pulmonary Critical Care", <%= @pcc_point_total %>, "red"]
                    ]);
                        
                    view = new google.visualization.DataView(data);
                    view.setColumns([0, 1,
                        {
                            calc: "stringify",
                            sourceColumn: 1,
                            type: "string",
                            role: "annotation"
                        },
                    2]);

                    options = {
                        bar: { groupWidth: "95%" },
                        legend: { position: "none" },
                    };
                    chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
                    chart.draw(view, options);
                }

                if(window.attachEvent) {
                    window.attachEvent('onresize', function() {
                        chart.draw(view, options);
                    });
                } else if(window.addEventListener) {
                    window.addEventListener('resize', function() {
                        chart.draw(view, options);
                    }, true);
                } else {
                }

            </script>
            <div class="minor-container">
                <div id="columnchart_values"></div>
            </div>
        </div>
    <% end %>
    <div class="text-right">
        <%= link_to 'Save and Exit', '/questions/confirmation' %>
    </div>
</div>