config/routes.rb
Rails.application.routes.draw do
  get 'questions/confirmation'
  get 'questions/instructions'
  get 'questions/survey'
  get 'users/login'
  root 'users#login'
  resources :optionals
  resources :feedbacks
  resources :questions
  resources :responses
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    validates :experience, :future, :difficulty, presence: true
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:new, :create]
  before_action :credentials?, only: [:new, :create]
  before_action :admin?, except: [:new, :create]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all.order(sort_column(Feedback) + ' ' + sort_direction)
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(user_id: @current_user.user_id, is_gamified: @current_user.is_gamified, 
                experience: params[:experience], future: params[:future], difficulty: params[:difficulty])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to :root, notice: 'Thank you for participating in our survey.' }
        format.js
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:user_id, :experience, :future, :difficulty)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<div class="text-center">
<%= form_with(model: feedback, local: true) do |form| %>
  <h3>How would you rate your experience?</h3>
  <div class="flex-container">
  <table>
    <tr>
      <td><%= label_tag(:experience_1, "Very Unenjoyable") %></td>
      <td><%= label_tag(:experience_2, "Unenjoyable") %></td>
      <td><%= label_tag(:experience_3, "Neutral") %></td>
      <td><%= label_tag(:experience_4, "Enjoyable") %></td>
      <td><%= label_tag(:experience_5, "Very Enjoyable") %></td>
    </tr>
    <tr>
      <td><%= radio_button_tag(:experience, "1") %></td>
      <td><%= radio_button_tag(:experience, "2") %></td>
      <td><%= radio_button_tag(:experience, "3") %></td>
      <td><%= radio_button_tag(:experience, "4") %></td>
      <td><%= radio_button_tag(:experience, "5") %></td>
    </tr>
  </table>
  </div>

  <h3>Would you be willing to partake in surveys like this in the future?</h3>
  <div class="flex-container">
  <table>
    <tr>
      <td><%= label_tag(:future_1, "Very Unlikely") %></td>
      <td><%= label_tag(:future_2, "Unlikely") %></td>
      <td><%= label_tag(:future_3, "Neutral") %></td>
      <td><%= label_tag(:future_4, "Likely") %></td>
      <td><%= label_tag(:future_5, "Very Likely") %></td>
    </tr>
    <tr>
      <td><%= radio_button_tag(:future, "1") %></td>
      <td><%= radio_button_tag(:future, "2") %></td>
      <td><%= radio_button_tag(:future, "3") %></td>
      <td><%= radio_button_tag(:future, "4") %></td>
      <td><%= radio_button_tag(:future, "5") %></td>
    </tr>
  </table>
  </div>

  <h3>How difficult did you find this survey?</h3>
  <div class="flex-container">
  <table>
    <tr>
      <td><%= label_tag(:difficulty_1, "Very Easy") %></td>
      <td><%= label_tag(:difficulty_2, "Easy") %></td>
      <td><%= label_tag(:difficulty_3, "Neutral") %></td>
      <td><%= label_tag(:difficulty_4, "Hard") %></td>
      <td><%= label_tag(:difficulty_5, "Very Hard") %></td>
    </tr>
    <tr>
      <td><%= radio_button_tag(:difficulty, "1") %></td>
      <td><%= radio_button_tag(:difficulty, "2") %></td>
      <td><%= radio_button_tag(:difficulty, "3") %></td>
      <td><%= radio_button_tag(:difficulty, "4") %></td>
      <td><%= radio_button_tag(:difficulty, "5") %></td>
    </tr>
  </table>
  </div>
  <br>

  <div class="actions">
    <%= form.submit "Submit Feedback" %>
  </div>
<% end %>
</div>

<% if feedback.errors.any? %>
    <div class="text-center">
        <br>Please answer all questions before submitting.
    </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedbacks</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= sortable "user_id", Feedback %></th>
      <th><%= sortable "experience", Feedback %></th>
      <th><%= sortable "future", Feedback %></th>
      <th><%= sortable "difficulty", Feedback %></th>
      <th><%= sortable "created_at", Feedback %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.user_id %></td>
        <td><%= feedback.experience %></td>
        <td><%= feedback.future %></td>
        <td><%= feedback.difficulty %></td>
        <td><%= feedback.created_at %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', :responses %>

app/views/feedbacks/new.html.erb
<%= render 'form', feedback: @feedback %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @feedback.user_id %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @feedback.feedback %>
</p>

<p>
  <strong>Future:</strong>
  <%= @feedback.future %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @feedback.difficulty %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>