config/routes.rb
Rails.application.routes.draw do
  get 'questions/confirmation'
  get 'questions/instructions'
  get 'questions/survey'
  get 'users/login'
  root 'users#login'
  resources :optionals
  resources :feedbacks
  resources :questions
  resources :responses
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/optional.rb
class Optional < ApplicationRecord
    validates :response, length: { maximum: 1000 }
end

app/controllers/optionals_controller.rb
class OptionalsController < ApplicationController
  include Calculations
  before_action :set_optional, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:new, :create]
  before_action :credentials?, only: [:new, :create]
  before_action :admin?, except: [:new, :create]
  before_action :set_multiplier, only: [:new]

  # GET /optionals
  # GET /optionals.json
  def index
    @optionals = Optional.all.order(sort_column(Optional) + ' ' + sort_direction)
  end

  # GET /optionals/1
  # GET /optionals/1.json
  def show
  end

  # GET /optionals/new
  def new
    if @current_user.completed != 2**Question.all.count - 1
        flash[:danger] = 'Please complete the survey first'
        redirect_to :root and return
    end
    @has_responded = Optional.where(user_id: @current_user.user_id).count > 0
    @user_point_total = (calculate_user(@current_user) * @multiplier).floor
    @optional = Optional.new
  end

  # GET /optionals/1/edit
  def edit
  end

  # POST /optionals
  # POST /optionals.json
  def create

    # only save if the user input anything
    if !params[:response].empty?
        @optional = Optional.new(user_id: @current_user.user_id, is_gamified: @current_user.is_gamified, response: params[:response])
        @optional.save
    end

    # redirect to results
    redirect_to :new_optional

  end

  # PATCH/PUT /optionals/1
  # PATCH/PUT /optionals/1.json
  def update
    respond_to do |format|
      if @optional.update(optional_params)
        format.html { redirect_to @optional, notice: 'Optional was successfully updated.' }
        format.json { render :show, status: :ok, location: @optional }
      else
        format.html { render :edit }
        format.json { render json: @optional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /optionals/1
  # DELETE /optionals/1.json
  def destroy
    @optional.destroy
    respond_to do |format|
      format.html { redirect_to optionals_url, notice: 'Optional was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_optional
      @optional = Optional.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def optional_params
      params.require(:optional).permit(:user_id, :is_gamified, :response)
    end
end

app/helpers/optionals_helper.rb
module OptionalsHelper
end

app/views/optionals/_form.html.erb
<h3 class="text-center">You have finished the survey.</h3>
<% if @current_user.is_gamified %>
    <h4 class="text-center">You earned <%= @user_point_total %> points.</h4>
<% end %>

<div class="row">
    <div class="column side"></div>
    <div class="column middle">
        <div class="optional">
            <div class="flex-container">
            <div class="flex-container-vertical">
                <div class="container-text">
                    Thank you for completing this survey. The survey has now concluded. If you log-in again, 
                    you will be brought back to this page. Upon exiting, you will be automatically logged out. 
                </div>

                <% if @current_user.is_gamified %>
                    <br>
                    <div class="container-text">
                        Once the survey period has concluded and all responses are collected, you will receive 
                        an email containing the results of the competition.
                    </div>
                <% end %>
            </div>
            </div>
            <br>
            <% if !@has_responded %>
                <div class="flex-container">
                    <div class="container-text">
                        Please feel free to leave any comments, questions, or concerns in the box below.
                        This box is optional. It is not part of the study. Once you submit your response, you 
                        will not be able to submit another response.
                    </div>
                </div>
                <br>
                <%= form_with(model: optional, local: true) do |form| %>
                <div class="flex-container">
                    <div class="container">
                        <textarea name="response" maxlength="1000" rows="5" placeholder="Character limit 1000"></textarea>
                    </div>
                </div>
                <div class="form-actions">
                    <%= form.submit "Submit" %>
                </div>
                <% end %>
            <% end %>
            <div class="text-center">
                <%= link_to 'Exit', :new_feedback %>
            </div>
        </div>
    </div>
    <div class="column side"></div>
</div>

app/views/optionals/edit.html.erb
<h1>Editing Optional</h1>

<%= render 'form', optional: @optional %>

<%= link_to 'Show', @optional %> |
<%= link_to 'Back', optionals_path %>

app/views/optionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Optionals</h1>


<table class="table">
  <thead>
    <tr>
      <th><%= sortable "user_id", Optional %></th>
      <th><%= sortable "is_gamified", Optional %></th>
      <th><%= sortable "response", Optional %></th>
      <th><%= sortable "created_at", Optional %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @optionals.each do |optional| %>
      <tr>
        <td><%= optional.user_id %></td>
        <td><%= optional.is_gamified %></td>
        <td><%= optional.response %></td>
        <td><%= optional.created_at %></td>
        <td><%= link_to 'Destroy', optional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', :responses %>

app/views/optionals/new.html.erb
<%= render 'form', optional: @optional %>

app/views/optionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @optional.user_id %>
</p>

<p>
  <strong>Is gamified:</strong>
  <%= @optional.is_gamified %>
</p>

<p>
  <strong>Response:</strong>
  <%= @optional.response %>
</p>

<%= link_to 'Back', optionals_path %>